### ISSUE TITLE
broswer.d.ts not found

### ISSUE THREAD

**Issue by ferredel** [cstefanache/angular2-img-cropper#1]
Hi!

Just using image cropper with webpack-starter-pack.

When i try to build:prod just crashes and throws:

`File '/node_modules/ng2-img-cropper/node_modules/angular2/typings/browser.d.ts' not found.`

Maybe is related with: https://github.com/AngularClass/angular2-webpack-starter#custom-type-definitions

**Comment by cstefanache** [comment]
Just published version 0.2.2 without the npm dependency and tested with starter pack. Should be ok now! Just let me know if everything is ok on your side

**Comment by ferredel** [comment]
Yay!

That works!

Thankyou :)
