### ISSUE TITLE
Issues when installing from fork of this repo

### ISSUE THREAD

**Issue by CelsoSantos** [cstefanache/angular2-img-cropper#100]
Hello,

I'm doing some experiments to see how much (if any) of a performance hit it is to bind the canvas element to jpg rather than png.
Using png is extremely heavy when doing the crop since images are loaded in memory.

However, everytime I do `npm i celsosantos/angular2-img-cropper` all I get is an almost empty folder.
I've been able to do some more ops and get some more files when installing from my forks `master` but that doesn't seem right, so, what am I doing wrong? Why can't I install the package from my fork as if it was the original?
In this repo everything installs fine, but not on mine.

Could you give an overview of the install process and what happens during this process so I can try to find out what I'm doing wrong?

Best Regards,
Celso Santos

**Comment by cstefanache** [comment]
Please check if 0.7.5 is working for you - if everything is ok please close the issue

**Comment by CelsoSantos** [comment]
Hello @cstefanache thank you.

I'll check and get back to you ASAP.

Thank you

**Comment by CelsoSantos** [comment]
Hello @cstefanache ,

I can confirm the new version does improve performance when using jpg images.
I wouldn't say that it's 100% perfect, but I think I may be noticing the same as in #96 .

I may be at fault as well since I use 3 croppers in one page, but jpeg does work.

Thank you!
