### ISSUE TITLE
 Error on fetch for ng2-img-cropper.js?

### ISSUE THREAD

**Issue by ghatul** [cstefanache/angular2-img-cropper#101]
@cstefanache 
 i use https://github.com/vyakymenko/angular2-seed-express this seed for my project .
on development build it work without any error but on production build it stuck with error

 'build.bundles.app' errored after 732 ms
[12:44:29] Error on fetch for ng2-img-cropper.js at file:///home/Projects/seed/node_modules/ng2-img-cropper.js
        Loading dist/tmp_client/app/app.module.js
        Loading dist/tmp_client/app/main.js
        Error: ENOENT: no such file or directory, open '/home/Projects/seed/node_modules/ng2-img-cropper.js'
    at Error (native)
[12:44:29] 'build.prod' errored after 14 s
[12:44:29] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for ng2-img-cropper.js at file:///home/Projects/seed/node_modules/ng2-img-cropper.js
        Loading dist/tmp_client/app/app.module.js
        Loading dist/tmp_client/app/main.js
        ENOENT: no such file or directory, open '/home/Projects/seed/node_modules/ng2-img-cropper.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open '/home/Projects/seed/node_modules/ng2-img-cropper.js'
Stack:
Error on fetch for ng2-img-cropper.js at file:///home/Projects/seed/node_modules/ng2-img-cropper.js
        Loading dist/tmp_client/app/app.module.js
        Loading dist/tmp_client/app/main.js
        Error: ENOENT: no such file or directory, open '/home/Projects/seed/node_modules/ng2-img-cropper.js'
    at Error (native)

my seed on angular 2.1.2
with latest node and  npm.
whats going wrong here?

**Comment by ghatul** [comment]
hi @cstefanache,

i tried this issue but i fail to find out whats going wrong .
may be it not getting reference after minify files from node_modules? on production build.
on development build it not getting any error. minify task is not on development build?
dont know........?

**Comment by ghatul** [comment]
Please sir guide me my project deployment is stuck because of this issue

**Comment by KANekT** [comment]
@ghatul go to hell

**Comment by cstefanache** [comment]
@ghatul: how do you create the bundle? can you please show the configuration for build?

**Comment by cstefanache** [comment]
Are you doing any tree shaking

**Comment by ghatul** [comment]
@cstefanache 
i use => https://github.com/vyakymenko/angular2-seed-express as seed for my project
 You  can also see all file configuration on above git repo. 

my gulp file production configuration is:
gulp.task('build.prod', (done: any) =>
  runSequence('check.tools',
              'clean.prod',
              'tslint',
              'css-lint',
              'build.assets.prod',
              'build.html_css',
              'copy.prod',
              'copy.server.js.prod',
              'build.server.prod',
              'build.js.prod',
              'build.bundles',
              'build.bundles.app',
              'minify.bundles',
              'build.index.prod',
              'copy.server.assets',
              done));
}

and
this is configuration for that bundle.=>

import { join } from 'path';
import * as Builder from 'systemjs-builder';

import Config from '../../config';

const BUNDLER_OPTIONS = {
  format: 'cjs',
  minify: true,
  mangle: false
};

/**
 * Executes the build process, bundling the JavaScript files using the SystemJS builder.
 */
export = (done: any) => {
  let builder = new Builder(Config.SYSTEM_BUILDER_CONFIG);
  builder
    .buildStatic(join(Config.TMP_CLIENT_DIR, Config.BOOTSTRAP_FACTORY_PROD_MODULE),
      join(Config.JS_DEST, Config.JS_PROD_APP_BUNDLE),
      BUNDLER_OPTIONS)
    .then(() => done())
    .catch((err: any) => done(err));
};

**Comment by ghatul** [comment]
hi @cstefanache 

your component written in typescript and on production build it not get compiled into js files ....is that reason?may be.....?

**Comment by cstefanache** [comment]
Released 0.7.6 with JS files as well - please check

**Comment by cstefanache** [comment]
Closing issue ... no news from the reporter
