### ISSUE TITLE
context.ngAfterViewInit is not a function

### ISSUE THREAD

**Issue by NaLLiFFuNT** [cstefanache/angular2-img-cropper#103]
I did the everything as well as in your example & got following error when open the page with cropper
TypeError: self._ImageCropperComponent_2_4.context.ngAfterViewInit is not a function

**Comment by cstefanache** [comment]
Please checkout the new code, upgrade your typescript to 2.1.4 and check again

**Comment by cstefanache** [comment]
If everything is ok please close both #103 and #102

**Comment by cstefanache** [comment]
Any status? (0.7.6 was released with new fixes)

**Comment by cstefanache** [comment]
Closing due to cleanup - reopen if occurs after changes
