### ISSUE TITLE
exif.ts "Property 'status' does not exist on type 'XMLHttpRequestEventTarget'. "

### ISSUE THREAD

**Issue by fahad-nxvt** [cstefanache/angular2-img-cropper#104]
i am getting the following error. I am using Angular 2.1.2 and Version 0.7.1 of image cropper.

.../node_modules/ng2-img-cropper/src/exif.ts:317:22
 Property 'status' does not exist on type 'XMLHttpRequestEventTarget'.

Anyone knows how to fix it?

**Comment by fahad-nxvt** [comment]
Updated to 0.7.5 but the problem persists. Any help would be highly appreciated.

**Comment by cstefanache** [comment]
I am on vacation till 15 th. I might not be able to fix anything till then.
I can merge pull requests if you have a fix. I assume setting to type any
would fix the problem temporarly

**Comment by fahad-nxvt** [comment]
@cstefanache Thank you for prompt response. Will wait for you to have a gud look at it. Will wait for you to come back. Thanks

**Comment by travislaynewilson** [comment]
I can confirm that I'm experiencing the same issue using v0.7.5.

**Comment by cstefanache** [comment]
Released on 0.7.6
