### ISSUE TITLE
Customizable color palette

### ISSUE THREAD

**Issue by mattes42** [cstefanache/angular2-img-cropper#11]
It would be great if the colors were customizable via CropperSettings. That would make it a lot easier to adjust the cropper to corporate style guides. In terms of customization it would be awesome if one could pass down a css class name to the file input.

**Comment by cstefanache** [comment]
Fixed with with latest commit. Will be released soon:

![image](https://cloud.githubusercontent.com/assets/3071201/16226713/6a678380-37b5-11e6-9207-1b207d5a8a3f.png)



        this.cropperSettings.cropperDrawSettings.strokeColor = 'rgba(255,255,255,1)';
        this.cropperSettings.cropperDrawSettings.strokeWidth = 1;
