### ISSUE TITLE
Have the result image dimension be determined by how the user cropped

### ISSUE THREAD

**Issue by waynechaw** [cstefanache/angular2-img-cropper#116]
Currently, the dimension of the result image is predetermined by setting. Is it possible to make the result image dimension based on how the user cropped? For example, the result image would be a rectangle if the user cropped a rectangle out of a square image.

**Comment by cstefanache** [comment]
Here is a sample: you can do calculations in order to do scaling if necessary on event. 
https://plnkr.co/xeacNxaeHbZSpttUVGzh

Is this a good solution?

**Comment by waynechaw** [comment]
Hi Cornel, thanks for the fast response. 

I am using the noFileInput option so it appears I will not have access to the cropped function to do the calculation. Do you have a solution?

Thanks again

**Comment by cstefanache** [comment]
cropped is an event listener for onCrop event triggered by img-cropper component. If you bind it then you should have access to it.
eg:
(onCrop)="cropped($event)"

**Comment by waynechaw** [comment]
thank you
