### ISSUE TITLE
Method reset or clear, after upload image

### ISSUE THREAD

**Issue by alejandroledesma** [cstefanache/angular2-img-cropper#118]
Hi,

I need a method to clear or reset uploader, after upload image. I searched for info of this case and I did not find anything.

Could someone help me??

Regards

**Comment by aalgabre** [comment]
anything update on this issue?

Regards
drew

**Comment by cstefanache** [comment]
fixed - will be released in 0.8 soon

**Comment by Mihai-B** [comment]
Nice
