### ISSUE TITLE
Highlighting due to click and drag

### ISSUE THREAD

**Issue by PierreRochard** [cstefanache/angular2-img-cropper#120]
If you click and drag to increase the crop size past the canvas' edge then it starts highlighting text.

**Comment by cstefanache** [comment]
This is not a cropper issue. Please add this to your CSS: 
body{

    -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
    -khtml-user-select: none; /* Konqueror HTML */
    -moz-user-select: none; /* Firefox */
    -ms-user-select: none; /* Internet Explorer/Edge */
    user-select: none; /* Non-prefixed version, currently
                                  supported by Chrome and Opera */

}
