### ISSUE TITLE
Cropped image file size is larger than the original image file size

### ISSUE THREAD

**Issue by kiddojrme** [cstefanache/angular2-img-cropper#134]
I tried to crop an image with dimensions of 2048x505 pixels and has 125KB file size only. But the cropped image has dimensions of 6000x696 pixels and now has 400KB file size. 

This is really a **major** issue.

These are the settings I used
> this.cropperHeroSettings.width = 1400;
> this.cropperHeroSettings.height = 400;
> this.cropperHeroSettings.minWidth = 1400;
> this.cropperHeroSettings.minHeight = 100;
> this.cropperHeroSettings.canvasWidth = 600;
> this.cropperHeroSettings.canvasHeight = 280;
> this.cropperHeroSettings.rounded = false;
> this.cropperHeroSettings.keepAspect = false;
> this.cropperHeroSettings.noFileInput = true;
> this.cropperHeroSettings.preserveSize = true;
> this.cropperHeroSettings.minWithRelativeToResolution = true;
> this.cropperHeroSettings.responsive = false;

**Comment by cstefanache** [comment]
Will have to add a compression as parameter to the settings

**Comment by kiddojrme** [comment]
ETA on this?

**Comment by cstefanache** [comment]
done - will be released soon

**Comment by kiddojrme** [comment]
Thank you so much. Will wait for the next release. 😉

**Comment by cstefanache** [comment]
It should be already released with 0.8.0
