### ISSUE TITLE
Allow user to opt for rounded bounds for selection

### ISSUE THREAD

**Issue by cstefanache** [cstefanache/angular2-img-cropper#14]

**Comment by gfranco93** [comment]
I'm working on it.

**Comment by cstefanache** [comment]
I was thinking about something like this: (might need some changes on Bounds)
![image](https://cloud.githubusercontent.com/assets/3071201/16060586/ca3d8aa2-3288-11e6-8d5f-eb80c2801c0b.png)

**Comment by Mihai-B** [comment]
Please don't change this component like this. You are basically changing the way it works, and for me at least, I will not be able to use the cropper in my project.
So it is either supporting both ways, or keep the old square functionality.

Please let me know of your decision, so I know what to expect for the future.

**Comment by cstefanache** [comment]
No worries ... the component will not change the initial functionality. It will be added as an option.

**Comment by cstefanache** [comment]
hello @Mihai-B i've just released 0.4.2 and removed all .ts files from the published package.
please check the readme.md file (or plnkr) for js usage (if you used .ts files before)

**Comment by Mihai-B** [comment]
Ok. Thnx for the heads up
