### ISSUE TITLE
Not working first time

### ISSUE THREAD

**Issue by oztek22** [cstefanache/angular2-img-cropper#141]
Every time when I try to upload a new Image in cropper2(Also in example  given in runtime.) It isn't showing the 1st time after removing cache and then it works as expected.
Can you please look into this matter?

**Comment by cstefanache** [comment]
Can you please let me know the browser that you are using and describe reproducing steps?

**Comment by oztek22** [comment]
I'm using it in ng2-modal. I tried it on both chrome and firefox. and I only changed the cropperSetting which is as below.
```

 this.cropperSettings.width = 300;
        this.cropperSettings.height = 160;
        this.cropperSettings.keepAspect = true;

        this.cropperSettings.croppedWidth = 750;
        this.cropperSettings.croppedHeight = 400;


        this.cropperSettings.canvasWidth = 451.367;
        this.cropperSettings.canvasHeight = 180;

        this.cropperSettings.minWidth =  300;
        this.cropperSettings.minHeight = 160;

        this.cropperSettings.rounded = false;
        this.cropperSettings.minWithRelativeToResolution = false;

        this.cropperSettings.cropperDrawSettings.strokeColor = 'rgba(255,255,255,1)';
        this.cropperSettings.cropperDrawSettings.strokeWidth = 2;
        this.cropperSettings.noFileInput = true;

        this.data1 = {};



```

**Comment by oztek22** [comment]
Now it's working after adding delay in setImage.

```
let timeoutId = setTimeout(() => {
                          this.cropper2.setImage(image);
                        }, 10);
```
I think it's getting Image even before it's decoded or something.

**Comment by TeemoWan** [comment]
+1, on safari

------WebKitFormBoundaryBpQtBavqkrpJdE4n
Content-Disposition: form-data; name="photo"; filename="avatar.png"
Content-Type: application/octet-stream


------WebKitFormBoundaryBpQtBavqkrpJdE4n--

**Comment by cstefanache** [comment]
Tried on Chrome, Safari on Mac but unable to reproduce it. Can you please let me know which Env/Browser versions you use?

**Comment by TeemoWan** [comment]
0.8.3 OK

**Comment by cstefanache** [comment]
Thanks!
