### ISSUE TITLE
Make the canvas white or hide it until image is loaded

### ISSUE THREAD

**Issue by laura2489** [cstefanache/angular2-img-cropper#142]
This cropper works very well for me, but i cannot make the canvas white or hide it until an image is uploaded. Please help me: 
![image](https://cloud.githubusercontent.com/assets/6919922/23949036/414d8e30-098e-11e7-9c65-4d803016e773.png)

**Comment by cstefanache** [comment]
I am thinking about having emptyClass and class defined as settings on the CropperSettings that will be assigned on the Canvas native element - will this work for you?

**Comment by laura2489** [comment]
Hope so. I'll have to try it to know for sure, but it sounds like a good idea.

**Comment by cstefanache** [comment]
Fixed by adding:
 
this.cropperSettings1.cropperClass = 'custom-class';
this.cropperSettings1.croppingClass = 'cropping';


You can hide the cropper as such:
.custom-class {
   visibility: hidden;
}

.cropping {
  visibility: visible;
}

**Comment by sorakthunly** [comment]
@cstefanache I set the class and styled it as your instruction. But it doesn't work. I can't seem to target the input directly and style it too.

**Comment by sorakthunly** [comment]
@laura2489 how do you target and style the input field?

**Comment by kagutagu** [comment]
@sorakthunly you have to place the class inside your main stylesheet, not your component stylesheet.
