### ISSUE TITLE
Return value issue on imageCropper.ts

### ISSUE THREAD

**Issue by axtho** [cstefanache/angular2-img-cropper#145]
After updating to Angular 2.4.10 i am getting a `node_modules/ng2-img-cropper/src/imageCropper.ts (937,38): Not all code paths return a value.)`

This would be fixed with a simple 
```
public getDragTouchForID(id:any):CropTouch | undefined {
        for (let i = 0; i < this.currentDragTouches.length; i++) {
            if (id === this.currentDragTouches[i].id) {
                return this.currentDragTouches[i];
            }
        }
       return undefined;
    }
```

Many packages are upgrading to the latest version now, with that of course TS (e.g. angular-cli, material2). Did you check the package against Angular 4 yet? 

Thanks for the awesome work though ;)

**Comment by cstefanache** [comment]
Can you please open a pull request if it compiles on your side - would be great to have you as contributor if you already did the investigation

**Comment by cstefanache** [comment]
Fixed with PR - thanks
