### ISSUE TITLE
FileType

### ISSUE THREAD

**Issue by limpep** [cstefanache/angular2-img-cropper#150]
Hi, 

Trying to use fileType setting and understand what it does, but not sure if I have this correct. 

So if I set the FileType to 'jpg' and I upload a png, does this then set the png image to a jpg? Also should the base64 be set as jpg too? Thanks.

**Comment by cstefanache** [comment]
I did some refactoring and by default fileType is undefined. By default the cropper will try to preserve default image format. If defined will convert to preffered: 'image/png', 'image/jpeg' etc.

**Comment by limpep** [comment]
Just tested and its working as expected. Thanks.
