### ISSUE TITLE
compile error with angular4.0

### ISSUE THREAD

**Issue by zxmsdyz** [cstefanache/angular2-img-cropper#157]
after update pro to angular4.0, when i run ng serve  the console show error message like bottom:
`ERROR in ImageCropperModule is not an NgModule
webpack: Failed to compile.`

 the component can't work in angular4 env?

**Comment by adamkundrat** [comment]
We had same issue. I fixed it by using version "0.8.1"

I suspect this issue was caused by #148

**Comment by cstefanache** [comment]
Can you please try with 0.8.4 ? - unfortunately had to introduce .d.ts && .ts files again

**Comment by adamkundrat** [comment]
@cstefanache - it works both AOT and 4.0.0! Thanks mate!
