### ISSUE TITLE
Pinch-and-zoom feature

### ISSUE THREAD

**Issue by brightpixels** [cstefanache/angular2-img-cropper#16]
Are there any plans to include pinch-and-zoom feature?

**Comment by cstefanache** [comment]
Now it is :) for 0.4.5 - sometimes at the end of the week - probably

**Comment by cstefanache** [comment]
I have fixed touch events - tested on IPad and Android phone - I think that pinch and zoom will not be implemented for 0.4.5

**Comment by cstefanache** [comment]
Released 0.5.0 - you can give it a try!
