### ISSUE TITLE
Not maintaining size of actual Image

### ISSUE THREAD

**Issue by oztek22** [cstefanache/angular2-img-cropper#161]
I'm trying to upload Image of 4160 * 3120 size and using ng2 Image cropper to maintain the ratio of uploaded Image. but it is uploading fix sized (750* 400 ) Image every time regardless of the actual size of the cropper.

    this.cropperSettings2 = new CropperSettings();        
    this.cropperSettings2.width = 750;
    this.cropperSettings2.height = 400;
    this.cropperSettings2.keepAspect = true;

    this.cropperSettings2.croppedWidth = 750;
    this.cropperSettings2.croppedHeight = 400;

    this.cropperSettings2.canvasWidth = 427.367;
    this.cropperSettings2.canvasHeight = 224;

    this.cropperSettings2.minWidth = 750;
    this.cropperSettings2.minHeight = 400;

    this.cropperSettings2.rounded = false;
    this.cropperSettings2.minWithRelativeToResolution = false;

    this.cropperSettings2.cropperDrawSettings.strokeColor = 'rgba(255,255,255,1)';
    this.cropperSettings2.cropperDrawSettings.strokeWidth = 2;
    this.cropperSettings2.noFileInput = true;

    this.data2 = {};

Is it a bug or I'm doing something wrong?

**Comment by cstefanache** [comment]
Try setting preserveSize = true

**Comment by cstefanache** [comment]
also: do you use Angular 4? just reeased a compatible version and wondering if it works

**Comment by oztek22** [comment]
I tried that too not working...

Currently I'm working on angular 2.4.0 with cropper version 0.8.1
But I tried version 0.8.3 on angular4 and It's working same as in angular2.

**Comment by cstefanache** [comment]
I will get into that asap - will try to get it fixed by tomorrow

**Comment by cstefanache** [comment]
Fixed! Please check sample app (tab 3) changes for sample. It was strange that the preservation of size worked for me - but bad! will release 0.8.5 soon - you can check it in 2 hrs or so

**Comment by oztek22** [comment]
thanks it worked.

**Comment by cstefanache** [comment]
awesome

**Comment by oztek22** [comment]
but but but.....
Now minwidth(read minwidth and minheight) is not working.
I removed this line so It takes Image directly from the original Image.
I uploaded Image of 640*480 dimension than my cropper is going till 190*190 while minwidth is set to 300
this.cropperSettings2.minWithRelativeToResolution = false;

should I start a new Issue or it just minor calculation problem?

**Comment by cstefanache** [comment]
I have absolutely no idea. what is minWidth?

**Comment by oztek22** [comment]
this.cropperSettings2.minWidth = 300;
this.cropperSettings2.minHeight = 300;

this things which stop your cropper to go below this width

**Comment by cstefanache** [comment]
ah... got it... it happens when keppAspect = false;

sorry for that - let me get into it - can you please open another issue?

**Comment by oztek22** [comment]
love to😆
