### ISSUE TITLE
Image pixels on the canvas [enhancement]

### ISSUE THREAD

**Issue by daco** [cstefanache/angular2-img-cropper#17]
Hi,

It seems that the image pixels on the canvas are one on one. Is there a way to load a hires image on a small canvas, but have the cropped image (the {{image.image}}) to have more pixels than the canvas?
I can do this with css, set the width of the canvas (much) smaller than cropperSettings.canvasWidth, and thats what I'm trying to achieve. But the canvas interface becomes too small and unresponsive if I do that.
Is there a valid way to do this?

**Comment by cstefanache** [comment]
the fix is already in progress. 
will be fixed and released soon. is this a hi-prio for you?

**Comment by daco** [comment]
Great!
I can work with it right now, but it's good to know that a fix is in the works. I can't release the app if this is not fixed, but there's still a long way to go before I reach that point!
Thanks!

**Comment by cstefanache** [comment]
Fixed with with latest commit. Will release soon.
