### ISSUE TITLE
requires a peer of @angular/common@4.0.0 but none was installed?

### ISSUE THREAD

**Issue by miliu99** [cstefanache/angular2-img-cropper#176]
I got this error when I install this cropper:

```
npm WARN ng2-img-cropper@0.8.6 requires a peer of @angular/common@4.0.0 but none was installed.
npm WARN ng2-img-cropper@0.8.6 requires a peer of @angular/compiler@4.0.0 but none was installed.
npm WARN ng2-img-cropper@0.8.6 requires a peer of @angular/core@4.0.0 but none was installed.
```

but I'm using newer versions as

  ```
"dependencies": {
    "@angular/animations": "^4.0.1",
    "@angular/common": "^4.1.0-beta.0",
    "@angular/compiler": "^4.1.0-beta.0",
    "@angular/compiler-cli": "^4.1.0-beta.0",
    "@angular/core": "^4.1.0-beta.0",
    "@angular/forms": "^4.1.0-beta.0",
    "@angular/http": "^4.1.0-beta.0",
    "@angular/platform-browser": "^4.1.0-beta.0",
    "@angular/platform-browser-dynamic": "^4.1.0-beta.0",
    "@angular/platform-server": "^4.1.0-beta.0",
    "@angular/router": "^4.1.0-beta.0",
```

What's wrong?

**Comment by Serginho** [comment]
Same problem. I would use: "^4.0.0"

**Comment by limpep** [comment]
It is just a warning you can ignore it.

**Comment by dalibor983** [comment]
Does this will be resolved soon?

**Comment by rogeliotrejo13** [comment]
npm WARN ionic-angular@3.2.1 requires a peer of @angular/common@4.1.0 but none was installed.
npm WARN ionic-angular@3.2.1 requires a peer of @angular/compiler@4.1.0 but none was installed.
npm WARN ionic-angular@3.2.1 requires a peer of @angular/compiler-cli@4.1.0 but none was installed.
npm WARN ionic-angular@3.2.1 requires a peer of @angular/core@4.1.0 but none was installed.
npm WARN ionic-angular@3.2.1 requires a peer of @angular/forms@4.1.0 but none was installed.
npm WARN ionic-angular@3.2.1 requires a peer of @angular/http@4.1.0 but none was installed.
npm WARN ionic-angular@3.2.1 requires a peer of @angular/platform-browser@4.1.0 but none was installed.
npm WARN ionic-angular@3.2.1 requires a peer of @angular/platform-browser-dynamic@4.1.0 but none was installed.
npm WARN ionic-angular@3.2.1 requires a peer of rxjs@5.1.1 but none was installed.
npm WARN ionic-angular@3.2.1 requires a peer of zone.js@^0.8.10 but none was installed.

same problem...

**Comment by cstefanache** [comment]
I am going to release 0.8.9 soon with ^4.0.0 fix
