### ISSUE TITLE
The npm package does not includes the .js files (only the .ts ones)

### ISSUE THREAD

**Issue by msaelices** [cstefanache/angular2-img-cropper#2]
This implies this kind of errors using the components:
`Cannot find module 'ng2-img-cropper/src/imageCropper' from ... `

**Comment by cstefanache** [comment]
I will update the package as soon as I test it with Angular 2.0.0-RC1

**Comment by cstefanache** [comment]
Changed package to work with angular RC1 and publish js files from dist
