### ISSUE TITLE
Smaller cropp area

### ISSUE THREAD

**Issue by Mihai-B** [cstefanache/angular2-img-cropper#21]
Is there a way to set the minimul cropp area?
I know in the cropper settings you can set up the initial cropp area size, but I would like to be able to set the minimum cropp area size.(and I need the cropp area size to be **smaller** then the current minimum cropp size).

Is this possible, or we have to implement this feature ?

**Comment by cstefanache** [comment]
At the moment there is no possibility. I set it up as an enhancement of 0.4.6 
Won't reach 0.4.5 unfortunately that will be launched tomorrow

**Comment by cstefanache** [comment]
Fixed on 0.4.5 - please check the option to set to canvas or original screen resolution

**Comment by Mihai-B** [comment]
Just tested and works perfectly. Thnx for the quick change!
