### ISSUE TITLE
how to setup for angular 4 project?

### ISSUE THREAD

**Issue by raviji** [cstefanache/angular2-img-cropper#214]
First of all thanks for developed this awesome one. If this is working for angular 4 then change the readme doc in front. Am unable to implement this in my project.

**Comment by meronbrouwer** [comment]
I have got this working in Angular4. You can find the code in this repo: https://github.com/gurpsdomain/GurpsyMcGurpsFace. 
Look at the portaitUpdaterDialog: https://github.com/gurpsdomain/GurpsyMcGurpsFace/tree/master/src/app/components/dialog/model-updaters/portrait-updater-dialog

**Comment by ClaudioKirchmair** [comment]
If you haven't managed to implement it then here is what I did ;)
Add the ImageCropperModule to your app.module.ts (or whatever module you want to use it in).
...
import { ImageCropperModule } from 'ng2-img-cropper';

@NgModule({
  imports: [
    ...
    ImageCropperModule,
    ...
})

You can see how to add it to your component it in the following Plnkr (not by me):
https://embed.plnkr.co/V91mKCNkBQZB5QO2MUP4/

**Comment by web-dave** [comment]
this repo is deprecated. But this comp will be maintained by me at https://github.com/web-dave/ngx-img-cropper
