### ISSUE TITLE
can't change canvas height & width in chrome

### ISSUE THREAD

**Issue by sridevips** [cstefanache/angular2-img-cropper#22]
I can't able to change my canvas size in chrome browser. Its perfectly work fine in firefox browser.
How can i solve this problem?

**Comment by cstefanache** [comment]
Please let me know if you have the same issue on this plunker:
https://embed.plnkr.co/9QMkQQea8tLfFzGVQOzQ/

**Comment by sridevips** [comment]
Yes... Same like this.

**Comment by cstefanache** [comment]
You are talking about the cropping canvas?
Can you paste a screenshot?

This is how gets rendered for me:
![image](https://cloud.githubusercontent.com/assets/3071201/16414249/41def634-3d3f-11e6-9708-53f80cacd19f.png)

**Comment by sridevips** [comment]
This is my error image which is not set in chrome
![error](https://cloud.githubusercontent.com/assets/17405523/16415286/29162300-3d5a-11e6-8c13-5e14d951c304.png)

**Comment by cstefanache** [comment]
I think that I do not understand the problem.
Seems that your cropping canvas has a 400x300 size (that can be changed via canvasSettings canvasWidth, canvasHeight). The resulting image will be saved as base64 data inside a data object that you pass to the cropper. The cropping canvas size cannot be changed at runtime.

Also can you please upgrade to cropper 0.4.6? (seems like you have an older version)
Can you please paste a comparison image between firefox and chome to understand the actual and desired functionality?

**Comment by sridevips** [comment]
Ya sure.. Here I attached screen which i get perfectly right in firefox. My cropper version is 
"ng2-img-cropper":"0.2.2"
![error1](https://cloud.githubusercontent.com/assets/17405523/16416106/41b6f502-3d5e-11e6-8cde-2577bbeecc8c.png)

I can't move or change size in chrome. but its correctly working fine in firefox.

**Comment by cstefanache** [comment]
First, please try to upgrade to 0.4.6.
As far as I understand you cannot drag the corners to crop the image right?

**Comment by sridevips** [comment]
yes i cannot drag any corners in any side. ok i'll upgrade to 0.4.6

**Comment by cstefanache** [comment]
Any news?

**Comment by cstefanache** [comment]
Is this still an issue?
