### ISSUE TITLE
Ability to style the file input button

### ISSUE THREAD

**Issue by vagadoo** [cstefanache/angular2-img-cropper#23]
Hi. Cool component! I would like to be able to style the input button. Is there any way I can pass a css class to the button or even pass a customised button as ng-content?

**Comment by cstefanache** [comment]
The fastest way to do this is like in this plunker:
https://embed.plnkr.co/P86QQuZs5GJlIelpdqlO/

CSS:
input[type="file"] {
  width: 60px;
	height: 20px;
	position: relative;
	float: left;
}

input[type="file"]:after {
  position: absolute;
  top: 0;
  bottom: 0;
  background-color: #FF0000;
  content: "Upload";
  color: #FFFFFF;
  display: block;
  width: 60px;
  height: 20px;
  padding-top: 5px;
  padding-left: 20px;
  border-radius: 3px;
}

canvas {
  display: block;
  margin-top: 30px;
}

**Comment by vagadoo** [comment]
Many thanks for the quick response.
Nice and neat solution.

**Comment by cstefanache** [comment]
Please let me know if you need a special format for the component template. I was having in mind changing a little bit the way it looks but I have no idea how to be generally available. CSS is the only solution that comes to my mind. If you have no suggestion you can close the issue.

thanks

**Comment by vagadoo** [comment]
how about transcluding the button with ng-content? That way I will be able to attach my own events to the button.
Another idea would be to be able to pass my own css class to the button. 
The component works fine for me now :+1:

**Comment by cstefanache** [comment]
Please see the comment at issue #26 

You can use an external file input.
![image](https://cloud.githubusercontent.com/assets/3071201/16728922/f0b230fe-4771-11e6-85e9-0ec6b406f7c5.png)
