### ISSUE TITLE
Size, dimension restriction feature.

### ISSUE THREAD

**Issue by davidbonachera** [cstefanache/angular2-img-cropper#24]
It would be nice to setup a minimum/maximum upload dimension and also define a maximum weight for the picture.

**Comment by davidbonachera** [comment]
I'm on it, how should it works if the filesize is to big or dimension are too large ? I just prompt an alert for the moment, not so user friendly.

**Comment by cstefanache** [comment]
Probably we should add a EventEmmiter at the component level and we can trigger different events - such as errors. What do you thing? 

I really think that error cases are handled very different on each app.

**Comment by davidbonachera** [comment]
Yes, i think it's the best way but we'll need a bit of documentation to explain how to catch the error. I'll finish this ASAP.

**Comment by cstefanache** [comment]
Any news on this issue?

**Comment by davidbonachera** [comment]
Didn't work on this lately, still using a quick hack to do that, i will take a look on this by this week.

**Comment by cstefanache** [comment]
moving to 0.6 - I need to release custom file upload and zoom / pinch

**Comment by cstefanache** [comment]
Moving to 0.7

**Comment by cstefanache** [comment]
This should be left as custom logic at the application level. One can fiddle with: preservation of resolution, width, height or can: $('img').src.length > MAX_LENGTH { do error }
