### ISSUE TITLE
When is the next version due?

### ISSUE THREAD

**Issue by meronbrouwer** [cstefanache/angular2-img-cropper#261]
The latest version 0.9.0 has been released some time back. Any plans on releasing a new version any time in the near future?

**Comment by StasGoshtein** [comment]
Great work dude.

Could you please work on Angular 5 compatibility?

**Comment by web-dave** [comment]
I just published a new version.
but the package name has changed!
npm i -S ngx-img-cropper
https://github.com/web-dave/ngx-img-cropper
