### ISSUE TITLE
Is this compatible with server rendering (Angular Universal)?

### ISSUE THREAD

**Issue by thibaultvanluchene** [cstefanache/angular2-img-cropper#262]
Title says it all...

**Comment by kvincent3** [comment]
Hi,
Did you try it ? I'm asking the same question.

**Comment by 5T0NkZ5V2j0H76y0** [comment]
Hi, didn't try it. 
Found out that I can use Croppie.js (jQuery) within the ngAfterViewInit hook when server side rendering.
Good luck.

**Comment by web-dave** [comment]
Hi, this project is deprecated. Please I inherited it and keep it up here
https://github.com/web-dave/ngx-img-cropper/
