### ISSUE TITLE
Angular 5 Support?

### ISSUE THREAD

**Issue by aiqingyuyan** [cstefanache/angular2-img-cropper#273]

**Comment by zijianhuang** [comment]
I am using NG 5.1 and cropper, no problem.

**Comment by nurf3d** [comment]
Why does the npm package @0.13.0 then say that it only supports angular ^4.0.0?

**Comment by web-dave** [comment]
After updating the source, npm hasn't published.
I'm fighting with it. hope to be done at the weekend.
Sorry folks.

**Comment by web-dave** [comment]
I just published a new version.
but the package name has changed!
npm i -S ngx-img-cropper
https://github.com/web-dave/ngx-img-cropper

**Comment by syedmkazmi** [comment]
Hiya,

Do we need to reinstall this now as `ngx-img-cropper`? Currently my apps using `angular2-img-cropper`?

**Comment by web-dave** [comment]
Yes.
