### ISSUE TITLE
Type ImageCropperComponent is part of the declarations of 2 modules...

### ISSUE THREAD

**Issue by AmirGilboa** [cstefanache/angular2-img-cropper#279]
in angular 4 project, created with cli, i have added angular2-img-cropper.
ng serve works fine, but **ng build -aot -prod** produces this error:

[1] ERROR in Error: Type ImageCropperComponent in 
D:/Projects/Angular2/projectX/node_modules/ng2-img-cropper/src/imageCropperComponent.d.ts 
is part of the declarations of 2 modules: 
ImageCropperModule in D:/Projects/Angular2/projectX/node_modules/ng2-img-cropper/src/imageCropperModule.d.ts 
and AppModule in D:/Projects/Angular2/projectX/client/app/app.module.ts! 
Please consider moving ImageCropperComponent in 
D:/Projects/Angular2/projectX/node_modules/ng2-img-cropper/src/imageCropperComponent.d.ts 
to a higher module that imports ImageCropperModule in 
D:/Projects/Angular2/projectX/node_modules/ng2-img-cropper/src/imageCropperModule.d.ts 
and 
AppModule in D:/Projects/Angular2/projectX/client/app/app.module.ts. 
You can also create a new NgModule that exports and includes ImageCropperComponent in 
D:/Projects/Angular2/projectX/node_modules/ng2-img-cropper/src/imageCropperComponent.d.ts 
then import that NgModule in ImageCropperModule in 
D:/Projects/Angular2/projectX/node_modules/ng2-img-cropper/src/imageCropperModule.d.ts 
and 
AppModule in 
D:/Projects/Angular2/projectX/client/app/app.module.ts.

Any idea?

**Comment by centigradeclemensP** [comment]
I think you have to import ImageCropperModule instead of declaring  ImageCropperComponent in your app.module.ts

**Comment by AmirGilboa** [comment]
it is imported, not declared. 
I would love to see a working angular 4 app or demo, that passes all stages including production.
that would eliminate the guesswork.
thanks.

**Comment by web-dave** [comment]
It works for us.
We imported the ImageCropperModule into our shared module, wich is imported in serveral modules.

**Comment by centigradeclemensP** [comment]
you imported the ICComponent not the ICModule - at least that is what the error report says:

...is part of the declarations of 2 modules:
...and AppModule in D:/Projects/Angular2/projectX/client/app/app.module.ts!

**Comment by web-dave** [comment]
this repo is deprecated. But this comp will be maintained by me at https://github.com/web-dave/ngx-img-cropper
