### ISSUE TITLE
How to get cropped image in ts file with a specified with and height

### ISSUE THREAD

**Issue by akshaysuresh92** [cstefanache/angular2-img-cropper#285]

**Comment by dhanarajp** [comment]
this.cropperSettings2.croppedWidth = 200;
 this.cropperSettings2.croppedHeight = 200;

**mentioned in sample usage also**

hope you asked this one only.

**Comment by akshaysuresh92** [comment]
@dhanarajp .. Thank you for the support.. My problem is i need a cropped image with height 56px and maximum width 160. height is fixed, width can be a maximum of 160px and a minimum of 56. Is it possible??

**Comment by web-dave** [comment]
is this a valid feature request?
I can privide params wich let you set a min/max for height and width.
Is that what you are looking for?

**Comment by web-dave** [comment]
BTW. this repo has been moved.
https://github.com/web-dave/ngx-img-cropper
You have to install it with the new name 
```
npm i -S ngx-img-cropper
```

**Comment by akshaysuresh92** [comment]
@web-dave  ya this is a valid feature .. 
will try it with " npm i -S ngx-img-cropper" and check

**Comment by web-dave** [comment]
I created a issue at the new repo for that with a link to this.
I'll do this in march i guess.

**Comment by akshaysuresh92** [comment]
Thank you for kind support

On Feb 14, 2018 4:35 PM, "David Müllerchen" <notifications@github.com>
wrote:

I created a issue at the new repo for that with a link to this.
I'll do this in march i guess.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cstefanache/angular2-img-cropper/issues/285#issuecomment-365569812>,
or mute the thread
