### ISSUE TITLE
Wrong cropper dimensions when cropAspect == sourceAspect [BUG]

### ISSUE THREAD

**Issue by gfranco93** [cstefanache/angular2-img-cropper#29]
When cropAspect == sourceAspect the cropper dimensions are smaller than they should be.
Plunker: https://embed.plnkr.co/GdlRu0q3EEWEnvnwRFom/

The following code is wrong:
(Extracted from [imageCropper](https://github.com/cstefanache/angular2-img-cropper/blob/5a8299ce429cc35e0312d90cfbece77cd8ed3fb0/src/ImageCropper.ts), lines 667 to 688)
```
if (cropAspect > sourceAspect) {
   var imageH = Math.min(w * sourceAspect, h);
    var cropW = imageH / cropAspect;
    tlPos = PointPool.instance.borrow(cX - cropW / 2, cY + imageH / 2);
    trPos = PointPool.instance.borrow(cX + cropW / 2, cY + imageH / 2);
    blPos = PointPool.instance.borrow(cX - cropW / 2, cY - imageH / 2);
    brPos = PointPool.instance.borrow(cX + cropW / 2, cY - imageH / 2);
} else if (cropAspect < sourceAspect) {
    var imageW = Math.min(h / sourceAspect, w);
    var cropH = imageW * cropAspect;
    tlPos = PointPool.instance.borrow(cX - imageW / 2, cY + cropH / 2);
    trPos = PointPool.instance.borrow(cX + imageW / 2, cY + cropH / 2);
    blPos = PointPool.instance.borrow(cX - imageW / 2, cY - cropH / 2);
    brPos = PointPool.instance.borrow(cX + imageW / 2, cY - cropH / 2);
} else {
    var imageW = Math.min(h, w);
    var cropH = imageW * cropAspect;
    tlPos = PointPool.instance.borrow(cX - imageW / 2, cY + cropH / 2);
    trPos = PointPool.instance.borrow(cX + imageW / 2, cY + cropH / 2);
    blPos = PointPool.instance.borrow(cX - imageW / 2, cY - cropH / 2);
    brPos = PointPool.instance.borrow(cX + imageW / 2, cY - cropH / 2);
}
```
I believe deleting the 'else' block and changing the 'else if' to just 'else' solves the problem. I'm going to submit a PR in a few hours.

**Comment by cstefanache** [comment]
![image](https://cloud.githubusercontent.com/assets/3071201/17034261/92279cd8-4f8a-11e6-8dd4-adfb0f6a5f84.png)

Are you talking about the fact that the resulting output is not filling the cropped canvas? 

![image](https://cloud.githubusercontent.com/assets/3071201/17034295/ba76be94-4f8a-11e6-93f5-107df2f68df9.png)

**Comment by cstefanache** [comment]
Also, is this affecting your production code? Do you need it released on NPM asap?

**Comment by gfranco93** [comment]
Don't worry, it just affects the dev code.

I'm talking about the fact that the cropper selector (I don't know if that's the proper way to call it, I'm referring to the white rectangle) it's not the size of the picture. The picture size is 200x150, and I setted the corpper selector size to 200x150, so it should cover the whole picture.

If I didn't make myself clear, you should try changing (in the plunker) the cropper selector size to 201x150 and see the difference it makes.

**Comment by cstefanache** [comment]
Thanks @gfranco93
