### ISSUE TITLE
Release update to NPM

### ISSUE THREAD

**Issue by sketchthat** [cstefanache/angular2-img-cropper#290]
With the recent merge to support `Angular 5` (https://github.com/cstefanache/angular2-img-cropper/pull/289), can the update be reflected in NPM?

https://www.npmjs.com/package/ng2-img-cropper

**Comment by web-dave** [comment]
Still waiting for the credentials to publish...
Are you in touch with @cstefanache?

**Comment by web-dave** [comment]
A fallback could be to rename it to ngx
-img-cropperand publish it. We would lose all npm history...

**Comment by web-dave** [comment]
as a quick fix i published https://www.npmjs.com/package/ngx-img-cropper

**Comment by sketchthat** [comment]
I've fired off an email and we will see what happens

**Comment by web-dave** [comment]
I'm in touch with him. thx

**Comment by web-dave** [comment]
OK. definetly new npm package.

```
npm i -S ngx-img-cropper
```
This repo is deprecated.

use this one for any further issues. and please make noise to let the world know about that new name.
https://github.com/web-dave/ngx-img-cropper
