### ISSUE TITLE
Restrict input file field to just images

### ISSUE THREAD

**Issue by cur3n4** [cstefanache/angular2-img-cropper#33]
It would be great if the input file would be restricted to images, or even better if the component allowed to configure it.

**Comment by cstefanache** [comment]
At the moment, the only way you can achieve this is to use a custom file input. Will be added as configuration on CropperSettings for the 0.6 - thanks for the suggestion

**Comment by cstefanache** [comment]
Fixed: added option: 
allowedFilesRegex:RegExp - (default: /.(jpe?g|png|gif)$/i) - Regex for allowed images

updated docs. Thanks for suggestion
