### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by sednanref** [cstefanache/angular2-img-cropper#34]
Hi, I was using this directive to test something and I have found that in Mozilla and Safari (newest versions) I can't move the  edges of the selected area, also, when I move the selected area I can move it outside the image which is a bit problematic. In chrome the directive works properly.

**Comment by cstefanache** [comment]
Multiple changes were made to fix Safari & Mozilla issues. I am going to close the issue for the moment. Can you please reopen it after (0.6 is released - probably today or tomorrow) ?

**Comment by sednanref** [comment]
Hi, thanks for considering this issue, but at least in Firefox, I can crop outside the image and I still can't move the corners to zoom in or zoom out the crop.
