### ISSUE TITLE
Add button to crop

### ISSUE THREAD

**Issue by gfranco93** [cstefanache/angular2-img-cropper#36]
I noticed that every time the cropper is moved or resized, the cropped picture is updated. This is not always desirable, especially when working with big pictures.
It would be nice to have the option to add a button so the user can choose when to crop the image.

Is there any interest in adding this feature?

**Comment by cstefanache** [comment]
This is interesting. I think that is a future feature to implement. Assigned it to milestone 0.7.
I am working on fixing the bugs for the 0.6 release.

**Comment by cstefanache** [comment]
Fixed with #191
