### ISSUE TITLE
Rounded cropper is not displayed in IE 11

### ISSUE THREAD

**Issue by StefanSinapov** [cstefanache/angular2-img-cropper#37]
Hi,

The rounded cropper is not displayed under IE. 
[https://plnkr.co/edit/V5FvvkkSYnkDYzyWQxJa?p=preview](https://plnkr.co/edit/V5FvvkkSYnkDYzyWQxJa?p=preview)

**Comment by cstefanache** [comment]
I am going to download a IE11 VM to test. 
Question: do you have any error in the console?

**Comment by StefanSinapov** [comment]
There is no errors, it function well, only the cropper is not transparent: 
![crop-img](https://cloud.githubusercontent.com/assets/5320446/17407410/d0eb3250-5a6f-11e6-905c-2efd57e2d9d5.gif)

**Comment by cstefanache** [comment]
Ah, thank you very much for the video!
Will try to fix it asap and deploy a new version. Might take few days due to busy schedule.

**Comment by cstefanache** [comment]
Removed darken background for rounded cropper due to browser compatibility.

**Comment by cstefanache** [comment]
Will be released with 0.6
