### ISSUE TITLE
Handling EXIF Image Orientation

### ISSUE THREAD

**Issue by frankfarzan** [cstefanache/angular2-img-cropper#40]
On iOS, the image is sometimes rotated 90 degrees. This seems to be a general
problem that involves reading EXIF data. Example:

https://github.com/fengyuanchen/cropper/issues/120

**Comment by tinquang** [comment]
I'm expecting the orientation option too

**Comment by cstefanache** [comment]
Is adding a rotate button on the image an option? If yes I can work this easily as soon as I get back from vacation.

**Comment by tinquang** [comment]
No, I mean the option auto rotate the image base on EXIF information, not the button to rotate the image.

**Comment by cstefanache** [comment]
Well look into it in few days. I found this solution: http://stackoverflow.com/questions/7584794/accessing-jpeg-exif-rotation-data-in-javascript-on-the-client-side will take some time because i have limited time in the next week.

**Comment by tinquang** [comment]
thanks, just take your time and have a good vacation :)

**Comment by cstefanache** [comment]
Added exif information

**Comment by cstefanache** [comment]
Added feature to parse exif information

**Comment by zjs1102** [comment]
I wanner a button to rotate the image thanks thanks !!
