### ISSUE TITLE
Error when using in Visual Sutdio Type FileReader is not assignable to type FileReader

### ISSUE THREAD

**Issue by naveedahmed1** [cstefanache/angular2-img-cropper#41]
Hi

I just tried to explore plugin and added some of the sample code from the plunker https://embed.plnkr.co/V91mKCNkBQZB5QO2MUP4/ to my app.

But when I try to compile my app in Visual Studio 2015, its giving below error:

`Type FileReader is not assignable to type FileReader. Property onloadend is missing in type FileReader`

Can you please guide?

**Comment by cstefanache** [comment]
In vacation at the moment. Will investigate as soon as i get some time.

**Comment by cstefanache** [comment]
Fixed! Will be released with 0.6

**Comment by naveedahmed1** [comment]
Thank you so much Cornel :)
