### ISSUE TITLE
Update to RC5

### ISSUE THREAD

**Issue by CelsoSantos** [cstefanache/angular2-img-cropper#42]
Hello,

Any chance this component can be updated to work with RC4 or RC5 (since 5 is already released)?
I'm seeing that package.json specifies RC1.

Best Regards

### EDIT ###
Installing on RC4 does not throw an npm error of unmet dependencies. It'll need further validation to confirm if indeed it works with more recent versions of Angular2

**Comment by cstefanache** [comment]
Fixed will be released with 0.6

**Comment by CelsoSantos** [comment]
Thanks :)
