### ISSUE TITLE
[request] Crop image information

### ISSUE THREAD

**Issue by tinquang** [cstefanache/angular2-img-cropper#45]
Hi, thanks for your new exif image feature, I want to request the feature that return crop image information (x,y, width, height of the cropper) beside the current base64 image content. Because my need is upload the original image with crop information, its size will smaller than base64 data.

Thanks in advance.

**Comment by Mihai-B** [comment]
A workaround for this is if you create your own ImageCropper object and pass it to the component, you have access to this data that you need.

**Comment by KingsDevelopment** [comment]
Can be done using the `onCrop` listener
