### ISSUE TITLE
ng2-img-cropper rc5 - cant bind to image since it isnt a known property of img-cropper

### ISSUE THREAD

**Issue by pedropvaz** [cstefanache/angular2-img-cropper#48]
Hello,
I'm trying to setup ng2-img-cropper in Angular2/RC5 and i'm facing the following error:

"Template parse errors: Can't bind to 'image' since it isn't a known property of 'img-cropper'... 
<img-cropper [ERROR ->][image]="data"></img-cropper>"

I have tried any several config variations without success. These included:
	- app.module.ts: including ImageCropperComponent in @NgModule imports and declarations
	- importing ImageCropperComponent, CropperSettings, Bounds in controller where i use the module
	- modified systemjs.config.js with:
		- map... 'ng2-img-cropper': 'node_modules/ng2-img-cropper'
		- packages... 'ng2-img-cropper': {main: 'index.js', defaultExtension: 'js'}
... but still the img-cropper module does not appear in the sources of the loaded app.

Anyone is facing similar issue or knows how to overcome this problem?

Best regards,
Pedro

**Comment by cstefanache** [comment]
Hello, 

I updated the sample plnkr: https://embed.plnkr.co/V91mKCNkBQZB5QO2MUP4/
to use rc.5 and it seems to work:
![image](https://cloud.githubusercontent.com/assets/3071201/18058383/c45475d6-6e1c-11e6-95bc-282ce0c767b5.png)

**Comment by pedropvaz** [comment]
hi, unfortunately still can't configure it in my environment for the same reasons mentioned previously
(plnkr is also not working in my browsers: the image simply doesn't appear in canvas after file selection. but probably the issues aren't connected)
any further help would be highly appreciated. best regards

**Comment by cstefanache** [comment]
There was a problem with the cropper that was fixed this morning and released on 6.0.1 - that is why the plnkr did not work - can you please try now so we can make sure that it is still reproducible for you with 6.0.1 as well?

**Comment by StefanSinapov** [comment]
Hi @cstefanache,
Can you export ngModule with the component, because with the angular rc.6 update they removed the deprecated directives prop from @Component decorator

**Comment by gauravdhiman** [comment]
I am also facing this. What is the solution for this ?
I am using ver 0.7.1 of image-cropper component. Any help would be appreciated.

**Comment by StefanSinapov** [comment]
What I currently do is to add `ImageCropperComponent` as declared in one of my modules.
```
import { NgModule } from '@angular/core';

import { ImageCropperComponent } from 'ng2-img-cropper';

import { SharedModule } from '../../shared.module';
import { AvatarUploadComponent }   from './avatar-upload.component';

@NgModule({
    imports: [SharedModule],
    exports: [AvatarUploadComponent],
    declarations: [
        // TODO: remove after angular2-img-cropper is updated
        ImageCropperComponent,
        AvatarUploadComponent],
    entryComponents: [AvatarUploadComponent],
    providers: [],
})
export class AvatarUploadModule { }
```

**Comment by jonscyriac** [comment]
Add ImageCropperComponent in AppModule declarations

import {ImageCropperComponent} from 'ng2-img-cropper';

@NgModule({
  declarations: [
    .....,
    ImageCropperComponent,
   ....
  ],
  imports: [
    .....
  ],
  providers: [.....],
  bootstrap: [AppComponent]
})
export class AppModule {}

**Comment by sunshineo** [comment]
@jonscyriac What you give causes another error

ERROR in Type ImageCropperComponent in /Users/gordon/workspace/CrewGuru/crewguru-web-ng2/node_modules/ng2-img-cropper/src/imageCropperComponent.d.ts is part of the declarations of 2 modules: ImageCropperModule in /Users/gordon/workspace/CrewGuru/crewguru-web-ng2/node_modules/ng2-img-cropper/src/imageCropperModule.d.ts and AppModule in /Users/gordon/workspace/CrewGuru/crewguru-web-ng2/src/app/app.module.ts! Please consider moving ImageCropperComponent in /Users/gordon/workspace/CrewGuru/crewguru-web-ng2/node_modules/ng2-img-cropper/src/imageCropperComponent.d.ts to a higher module that imports ImageCropperModule in /Users/gordon/workspace/CrewGuru/crewguru-web-ng2/node_modules/ng2-img-cropper/src/imageCropperModule.d.ts and AppModule in /Users/gordon/workspace/CrewGuru/crewguru-web-ng2/src/app/app.module.ts. You can also create a new NgModule that exports and includes ImageCropperComponent in /Users/gordon/workspace/CrewGuru/crewguru-web-ng2/node_modules/ng2-img-cropper/src/imageCropperComponent.d.ts then import that NgModule in ImageCropperModule in /Users/gordon/workspace/CrewGuru/crewguru-web-ng2/node_modules/ng2-img-cropper/src/imageCropperModule.d.ts and AppModule in /Users/gordon/workspace/CrewGuru/crewguru-web-ng2/src/app/app.module.ts.

**Comment by sunshineo** [comment]
You should import the module and put that in the imports section.

**Comment by IlmaZahil** [comment]
hello, I uploaded the image in the image cropper. after refreshing the page the image in the cropper disappear. there will be a default link for that. but I want to load my uploaded image in the image cropper until I input another image file in the image cropper. hope to get a solution as soon as possible.
