### ISSUE TITLE
Deploy release version before updating to Angular RC.5+

### ISSUE THREAD

**Issue by rayzru** [cstefanache/angular2-img-cropper#51]
There is a lot breaking changes from Angular RC.4 with ngModules, so I beg u deploy 0.6+ version for those who using RC.4 and below.

**Comment by cstefanache** [comment]
There will be a 0.6.5 release for RC.4

**Comment by cstefanache** [comment]
Released 0.6.4 and tested with readme plnkr - everything seems to be ok! Can you please close the issue when you test it?

**Comment by rayzru** [comment]
Yes, but please bump release here, if you don't mind.
https://github.com/cstefanache/angular2-img-cropper/releases

**Comment by cstefanache** [comment]
Done
