### ISSUE TITLE
Aspect ratio lost in settings

### ISSUE THREAD

**Issue by rayzru** [cstefanache/angular2-img-cropper#52]
There is some inconsistency in resulted image aspect ratio.
I have played the demo for a while with rectangular images, canvas and rectangular cropped area. 
So, actually resulted image sizes have a wrong aspect ratio and it seems like it's value has the sum of the aspect ratio of the crop area and the canvas in general.

(i'll show you plunker later)

Finally, I mean, if I ignore default sizes with similar sizes on each width/height, i will be confused about getting right values on actual result, Settings should be more intuitive and simple.

BTW, i just finished with uploader cropped area via XHR. 
It's very simple. we can include this function in future releases if u don't mind,

**Comment by KingsDevelopment** [comment]
Any updates? Is this still going on?

**Comment by mayconjcm** [comment]
Any updates?

**Comment by rayzru** [comment]
Personally, I think that's bad design to make things from based on a canvas design.

**Comment by cstefanache** [comment]
* **cropWidth**:*number - actual cropped image width
* **cropHeight**:*number - actual cropped image height

Added ^^^ in order to know the actual cropped image width/height on settings - updated test app as well - will be released today
