### ISSUE TITLE
Please add support for AoT compiler - Please add .metadata.json file in next release

### ISSUE THREAD

**Issue by naveedahmed1** [cstefanache/angular2-img-cropper#56]
The Angular team suggest that library vendors should also ship **.metadata.json** files. These files are produced automatically by ngc.

**Your might find below comments useful:**

https://github.com/angular/angular/issues/11262#issuecomment-244449696

https://github.com/angular/angular/issues/11262#issuecomment-244472000

https://github.com/angular/angular/issues/11262#issuecomment-244489405

Complete conversation (https://github.com/angular/angular/issues/11262)

**Comment by mayconjcm** [comment]
+1

**Comment by mayconjcm** [comment]
@cstefanache Any ETA for ngc compatibily? Thank you!

**Comment by cstefanache** [comment]
tring to do a deployment tomorrow with both ngc and js files

**Comment by mayconjcm** [comment]
=)

**Comment by cstefanache** [comment]
Not sure if is a good idea to treeshake a library. Wouldn't be better the compiler to be executed at application level rather than library level?

**Comment by mayconjcm** [comment]
Yes! I am using a lib "ng2-dragula" and there is executed at application level, not library level.

**Comment by cstefanache** [comment]
Tested ok with --aot and worked fine. closing issue
