### ISSUE TITLE
Plunker not working

### ISSUE THREAD

**Issue by kolkov** [cstefanache/angular2-img-cropper#64]
Hi!  Sample plunker example not working now.
https://www.npmjs.com/package/ng2-img-cropper
https://embed.plnkr.co/V91mKCNkBQZB5QO2MUP4/

![image](https://cloud.githubusercontent.com/assets/3740898/18848991/7c0ec032-8439-11e6-82bd-d4982438cd23.png)

**Comment by cstefanache** [comment]
Please try again today - plnkr was returning lots of 404 and 502s yesterday

**Comment by kolkov** [comment]
Thanks! )
