### ISSUE TITLE
Accessing the "cropper" var in ImageCropperComponent

### ISSUE THREAD

**Issue by TwanoO67** [cstefanache/angular2-img-cropper#65]
Hello,

Since the commit #d01889cdf690be16a918fbf03364c139ca507c2a
the cropper var is now private in ImageCropperComponent without any getter function.

So we can't change the image on the fly during crop

**Comment by KingsDevelopment** [comment]
use the `onCrop` listener.

**Comment by TwanoO67** [comment]
That doesn't fixe the issue at all.

the onCrop listener emit Bounds... not the cropper himself
`this.onCrop.emit(this.cropper.getCropBounds());`

We don't have access anymore to the cropper once it has been prepared.
It's a breaking change and we are forced to use this version since the update of NgModule and this one came at the same time...
Why couldn't you had a getCropper() function, or just set the input back to public restriction ?

**Comment by KingsDevelopment** [comment]
Noted, Pr's are welcome, in the meantime I'll see if I can find some time to add it.

**Comment by cstefanache** [comment]
Reintroduced with: aa68670a4b501eec2919975e82a838ea5ecbf8df - will be released today with 0.7
