### ISSUE TITLE
RC 6

### ISSUE THREAD

**Issue by ghatul** [cstefanache/angular2-img-cropper#67]
i am on rc6 and when hit npm install  ng2-img-cropper  

then ndoemodules/ng2-img-cropper/package.json --> install with rc5

on npm start getting  errors:
![screen shot 2016-09-29 at 2 31 05 pm](https://cloud.githubusercontent.com/assets/19589441/18947700/ca0e7a88-8651-11e6-8cb1-99a5341d6287.png)

please..

**Comment by KingsDevelopment** [comment]
Our dependencies in the package.json state:

    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0"

Try upgrading to angular 2.0.0 (the first official release) and try again.
