### ISSUE TITLE
How to use with ng2-uploader.

### ISSUE THREAD

**Issue by kolkov** [cstefanache/angular2-img-cropper#72]
Hi!
How to use cropper with ng2-uploader?
http://ng2-uploader.com/home

**Comment by KingsDevelopment** [comment]
This is not a help-desk, please keep your stuff related to angular2-img-cropper.

Tip:
If you can get any image date BEFORE the upload, just put it in the cropper and then upload.

**Comment by kolkov** [comment]
Duc does not work ... maybe the problem is on your side. ((
