### ISSUE TITLE
Error on translate for ng2-img-cropper....?

### ISSUE THREAD

**Issue by ghatul** [cstefanache/angular2-img-cropper#81]
i follow all your step which is given on your wiki page but i dont understand what is missing.......
on --npm 3.10.X
     --node 6.x.x
     --on angular stable 2.x.x
 If seed build in production mode: show following error:

 dist/prod/client/js/app.js
[19:31:36] 'build.bundles.app' errored after 1.74 s
[19:31:36] Error on translate for ng2-img-cropper/src/imageCropperModule.ts at file:///home//Desktop/development2.0/fullstack-seed/node_modules/ng2-img-cropper/src/imageCropperModule.ts
        Loading ng2-img-cropper/index.ts
        Loading dist/tmp_client/app/app.module.js
        Loading dist/tmp_client/app/main.js
        MultipleErrors: file:///home/pooja/Desktop/development2.0/tpl-web-fullstack-seed/node_modules/ng2-img-cropper/src/imageCropperModule.ts:6:1: Unexpected token @
file:///home/pooja/Desktop/development2.0/tpl-web-fullstack-seed/node_modules/ng2-img-cropper/src/imageCropperModule.ts:6:2: Semi-colon expected

**Comment by cstefanache** [comment]
do you have configured system.js to load library as TS instead of JS?
'ng2-img-cropper': {
      main: 'index.ts',
      defaultExtension: 'ts'
    },

**Comment by ghatul** [comment]
my seed config is:
...........................
'@angular/router/testing': 'node_modules/@angular/router/bundles/router-testing.umd.js',
      'ng2-img-cropper': 'npm:ng2-img-cropper@0.7.0',
      'app/*': '/app/*',
      // For test config
      'dist/dev/*': '/base/dist/dev/*',
      '*': 'node_modules/*
'},
-------------------------------------------------------------------
      'rxjs': {
        main: 'Rx.js',
        defaultExtension: 'js'
      },
      'ng2-img-cropper': {
        main: 'index.ts',
        defaultExtension: 'ts'
      },
    }

**Comment by cstefanache** [comment]
Are you using AngularJS 2.0.1?

**Comment by ghatul** [comment]
I have ^2.0.0 but when delete the node_modules and again install it then it taking higher 2.1.0 ,i saw  in modules package.json file show version 2.1.0

**Comment by ghatul** [comment]
when first i hit npm i ng2-img-cropper then it show 

UNMEETPEER DEPENDENCIE....

**Comment by cstefanache** [comment]
Strange... peer dependencies are (can you please check your npm packages?)
"@angular/common": "^2.1.0",
"@angular/compiler": "^2.1.0",
"@angular/core": "^2.1.0"

**Comment by ghatul** [comment]
My dependencies are:   
"@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/platform-browser-dynamic": "^2.0.0",
      after again npm install its module instaled at 2.1.0
'^' tag take latest version

**Comment by ghatul** [comment]
I use this seed  [https://github.com/vyakymenko/angular2-seed-express](url) .
It is not upddated to v2.1.0 but your module on v2.1.0 . may this stuck?

**Comment by cstefanache** [comment]
I will have a look today.

**Comment by cstefanache** [comment]
The problem is that we are publishing typescript files for the ng2-img-cropper package. I guess that the actual error on the console was: 404 ng2-img-cropper/index.ts.js because there was no transpiler defined in the systemjs folder.

here is the correct configuration:
SYSTEM_CONFIG_DEV: any = {
    defaultJSExtensions: true,
    transpiler: 'typescript',
    //typescript compiler options
    typescriptOptions: {
      emitDecoratorMetadata: true
    },
    packageConfigPaths: [
      `/node_modules/*/package.json`,
      `/node_modules/**/package.json`,
      `/node_modules/@angular/*/package.json`
    ],
    paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      '@angular/common': 'node_modules/@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'node_modules/@angular/compiler/bundles/compiler.umd.js',
      '@angular/core': 'node_modules/@angular/core/bundles/core.umd.js',
      '@angular/forms': 'node_modules/@angular/forms/bundles/forms.umd.js',
      '@angular/http': 'node_modules/@angular/http/bundles/http.umd.js',
      '@angular/platform-browser': 'node_modules/@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/router': 'node_modules/@angular/router/bundles/router.umd.js',

      '@angular/common/testing': 'node_modules/@angular/common/bundles/common-testing.umd.js',
      '@angular/compiler/testing': 'node_modules/@angular/compiler/bundles/compiler-testing.umd.js',
      '@angular/core/testing': 'node_modules/@angular/core/bundles/core-testing.umd.js',
      '@angular/http/testing': 'node_modules/@angular/http/bundles/http-testing.umd.js',
      '@angular/platform-browser/testing':
        'node_modules/@angular/platform-browser/bundles/platform-browser-testing.umd.js',
      '@angular/platform-browser-dynamic/testing':
        'node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic-testing.umd.js',
      '@angular/router/testing': 'node_modules/@angular/router/bundles/router-testing.umd.js',
      'ng2-img-cropper': 'node_modules/ng2-img-cropper/',

      'app/*': '/app/*',
      // For test config
      'dist/dev/*': '/base/dist/dev/*',
      '*': 'node_modules/*'
    },
    packages: {
      'ng2-img-cropper': {
        main: 'index.ts',
        defaultExtension: 'ts'
      }
    }
  };

we are going to publish the js versions in the next release

**Comment by cstefanache** [comment]
note that I have added: 
`
 transpiler: 'typescript', //typescript compiler options typescriptOptions: { emitDecoratorMetadata: true },
`

and 

`
   'ng2-img-cropper': 'node_modules/ng2-img-cropper/',
`

and 

`
  packages: {
  'ng2-img-cropper': {
    main: 'index.ts',
    defaultExtension: 'ts'
  }
 }
`

**Comment by ghatul** [comment]
@cstefanache 
thanku

**Comment by roshandhabekar** [comment]
@cstefanache  hey, can you please explain where u added above code, m getting confuse and facing same error with ionic 2
