### ISSUE TITLE
Cannot read property 'dragHandle' of undefined

### ISSUE THREAD

**Issue by JulioC** [cstefanache/angular2-img-cropper#83]
I've been getting reports from production of an exception 'Cannot read property 'dragHandle' of undefined' on [imageCropper.ts:927](https://github.com/cstefanache/angular2-img-cropper/blob/ec793b75aab2dd54ae0066a6bea4862078f7157c/src/imageCropper.ts#L927)

I was not able to reproduce the error nor I understand what impacts it has on the application. 

Maybe the fix would change the if to just `if (dragTouch)`

**Comment by cleever** [comment]
Same issue here.

**Comment by cstefanache** [comment]
fixed... will be release today. thanks
