### ISSUE TITLE
get unscaled crop of image

### ISSUE THREAD

**Issue by Popl7** [cstefanache/angular2-img-cropper#87]
I am trying to crop a part of a high resolution image.
The cropper makes the crop of the scaled down version as shown in the canvas.
Is it possible to have the crop from the unscaled image?

I have tested this on the plunkr and it behaves the same here.

This is wat I tried:
- Start the plunkr and upload a 4K/HD/720P test image of 4000x2000px
- Select the 720P screen size

And this is what I expected.
I expected to get a 720pixels height crop of the big image, shown scaled down to 200px.

It looks like this now:
![screen shot 2016-10-20 at 15 29 38](https://cloud.githubusercontent.com/assets/4224518/19561740/2187c268-96da-11e6-8e59-f9dd593c3a26.png)

This is a really rough crop of the scaled down 4000x2000px image.
The text is jagged and not crisp.

Is this something I can do with the cropper?

**Comment by Popl7** [comment]
This is the test image I used:
![digital_video_resolutions_ vcd_to_4k svg](https://cloud.githubusercontent.com/assets/4224518/19561869/96e870f2-96da-11e6-8a03-eef4e4a78215.png)

And this is a crop I made to show the cleanless of the 720P text:
![screen shot 2016-10-20 at 15 34 13](https://cloud.githubusercontent.com/assets/4224518/19561898/ae3bad96-96da-11e6-94ca-7cd3eadf6775.png)

**Comment by cstefanache** [comment]
Try using this when displaying the result:
<img [src]="data1.image" [width]="cropperSettings1.cropWidth" [height]="cropperSettings1.cropHeight">

(cropWidth instead of croppedWidth - I think this is a resolution problem

**Comment by Popl7** [comment]
This does show the crop in the resolution it should be, but not in the quality it should.
The base64 crop also hasn't changed so the data1.image is still low res.

![screen shot 2016-10-20 at 16 23 21](https://cloud.githubusercontent.com/assets/4224518/19563777/8b0892f6-96e1-11e6-83f9-82e1ff3e7ad7.png)

**Comment by Popl7** [comment]
it seams that the cropping is done on the canvas and not on a the original image.

**Comment by cstefanache** [comment]
Fixed! Unfortunately I need to to more tests to see if I am not breaking anything. How urgent is the fix?

![image](https://cloud.githubusercontent.com/assets/3071201/19564901/b46b893a-96ed-11e6-9ed7-b41ff6dd9b4f.png)

**Comment by Popl7** [comment]
:-) nice.
It is not breaking for us but a fix would be really nice.
Is there a way for us to try this before it is merged?

**Comment by cstefanache** [comment]
fixed ... will be released today

**Comment by Popl7** [comment]
I will try it this weekend.
Thx a lot for the lightning quick action!

**Comment by Popl7** [comment]
This works really good!
Thx again

**Comment by cstefanache** [comment]
well ... i will chek it in master, you checkout the code and do a npm run
all that will open a demo app in the browser.

thanks for the issue.

**Comment by renilbabu03** [comment]
I am facing the same issue. I also tried to open the demo app but is not opening. After doing 
npm run all. its giving me the following error

![pro](https://user-images.githubusercontent.com/18526147/32948328-e0aad548-cbc4-11e7-96cd-fd652d00d122.png)


Also the resolution of the image is degraded...Can you help me in this..
