### ISSUE TITLE
Not able to drag crop window when window too small

### ISSUE THREAD

**Issue by reingroot** [cstefanache/angular2-img-cropper#9]
When the cropper windowis below a certain size, it is no longer possible to move the cropper window. Instead I grab one of the 'size adjuster corners'.

It seems that the 'hit zone' for the 'size adjuster corners' are overlapping the hitzone for the drag/drop area.

Sorry for the cryptic terms. Hope you understand :)

At this size I can no longer drag/drop the cropper window:
![screen shot 2016-06-08 at 15 33 57](https://cloud.githubusercontent.com/assets/533047/15896077/f060052e-2d8e-11e6-9e06-311b0a37b89f.png)

**Comment by cstefanache** [comment]
Fixed in 0.4.0 - reduced touch size
