### ISSUE TITLE
TypeScript compiler errors with "'this' implicitly has type 'any'"

### ISSUE THREAD

**Issue by Tiliavir** [cstefanache/angular2-img-cropper#98]
TypeScript 2 with tsconfig
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noFallthroughCasesInSwitch": true,
    "skipLibCheck": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

and system.js
```
            'angular2-notifications': {
                main: 'components.js',
                defaultExtension: 'js'
            }
```

fails with:
node_modules/ng2-img-cropper/src/imageCropperComponent.ts(113,17): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
node_modules/ng2-img-cropper/src/imageCropperComponent.ts(114,31): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

From my point of view it is wrong that TypeScript checks this in the first place (in particular with "skipLibCheck": true), but you might want to fix it anyways ...

NB: I think it was already fixed with https://github.com/cstefanache/angular2-img-cropper/pull/93/files

**Comment by cstefanache** [comment]
please check and close the issue if fixed

**Comment by Tiliavir** [comment]
Fixed! Works like a charm, thanks a lot for your effort!
