### ISSUE TITLE
syntax error at index.ts at line 2

### ISSUE THREAD

**Issue by koheiokazaki** [cstefanache/angular2-img-cropper#99]
I have an error index.ts at line 2.

`export { ImageCropperModule } from './src/imageCropperModule';
`

Why???

**Comment by cstefanache** [comment]
Can you please paste the error? If everything compiles ok then this is an IDE problem and you should move the issue on their side

**Comment by koheiokazaki** [comment]
@cstefanache 
thanks for review.
Sorry, actually I was uninstalled img-cropper... 
but i want to use this.
maybe error is syntax error

**Comment by cstefanache** [comment]
Please reopen if you face this problem again
